//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmpoyeesDBEntities1 : DbContext
    {
        public EmpoyeesDBEntities1()
            : base("name=EmpoyeesDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();

            modelBuilder.Entity<employee>()
                .Property(e => e.FirstName)
                .HasColumnType("varchar(15)")
                .HasMaxLength(50)
                .IsRequired();


            modelBuilder.Entity<employee>()
                .Property(e => e.LastName)
                .HasColumnType("varchar(15)")
                .HasMaxLength(15)
                .IsRequired();
        }
    
        public virtual DbSet<employee> employees { get; set; }
      
    }
}
