//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee
    {
        public int ID { get; set; }
        public string EmployeeNo { get; set; }
        [Required]
        [MaxLength(16)]
        public string FirstName { get; set; }
        [Required]
        [MaxLength(16)]
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }

        [Required]
        [MaxLength(11)]
        [MinLength(11)]
        public string ContactNo { get; set; }
        public string EmailAddress { get; set; }
    }
}
